---
server_hostname: 'graindev'

src_dir: "/usr/local/src"

# php.ini
php_max_execution_time: '300'
php_memory_limit: "256MB"
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '100M'
php_upload_max_filesize: '100M'
php_date_timezone: 'US/Central'
php_sendmail_from: ""
php_sendmail_path: "php /home/vagrant/mail/sendmail.php"

# apc.ini
apc_rfc1867: '1'
apc_shm_size: '256M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# my.cnf
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# mysql
mysql_root_password: 'vagrant'

# apache
apache_server_admin: 'webmaster@graindev'
apache_server_alias: 'graindev'
