CREATE DATABASE `whooptee_drupal` DEFAULT CHARACTER SET `utf8`;
CREATE DATABASE `whooptee_designer` DEFAULT CHARACTER SET `utf8`;

CREATE USER 'whooptee'@'localhost' IDENTIFIED BY 'whooptee';

GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, GRANT OPTION, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON `whooptee_drupal`.* TO 'whooptee'@'localhost';
GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, GRANT OPTION, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON `whooptee_designer`.* TO 'whooptee'@'localhost';

FLUSH PRIVILEGES;
